<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDn4EbxM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDn4EbxM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDn4EbxM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDn4EbxM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDn4EbxM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Dn4EbxM',
    'container.build_id' => 'ce46446e',
    'container.build_time' => 1609704123,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDn4EbxM');
